services:

    app:
        container_name: php_app
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        image: space-guardians-app:local
        working_dir: /var/www/symfony
        ports:
            - '9000:9000'
        volumes:
            - ./app:/var/www/symfony
        environment:
            SYMFONY_ENV: ${SYMFONY_ENV}
        networks:
            - symfony
        depends_on:
            - db
        extra_hosts:
            - "host.docker.internal:host-gateway"

    web:
        image: nginx:latest
        container_name: nginx_web
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/symfony
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - symfony
        depends_on:
            - app
        environment:
            NGINX_HOST: ${NGINX_HOST}

    db:
        image: mysql:latest
        container_name: mysql_db
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_DATABASE_TEST: ${MYSQL_DATABASE_TEST}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/db/init.sh:/docker-entrypoint-initdb.d/init.sh
        networks:
            - symfony

    composer:
        image: composer:latest
        container_name: composer
        working_dir: /var/www/symfony
        volumes:
            - ./app:/var/www/symfony
        networks:
            - symfony

    ###> symfony/mailer ###
    mailer:
        container_name: mailer
        image: schickling/mailcatcher
        ports: [ "1025", "1080" ]
    ###< symfony/mailer ###

    react:
        image: node:18
        container_name: react_app
        volumes:
            - ./frontend:/usr/src/app
        working_dir: /usr/src/app
        command: sh -c "npm install && npm start"
        ports:
            - '3000:3000'
        networks:
            - symfony

volumes:
    db_data:

networks:
    symfony:
