# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Symfony

on:
    push:
        branches: [ "dev" ]
    pull_request:
        branches: [ "dev" ]

permissions:
    contents: read

jobs:
    symfony-tests:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Build Docker images
                uses: docker/bake-action@v4
                with:
                    pull: true
                    load: true
                    files: |
                        compose.yaml
                    set: |
                        *.cache-from=type=gha,scope=${{github.ref}}
                        *.cache-from=type=gha,scope=refs/heads/main
                        *.cache-to=type=gha,scope=${{github.ref}},mode=max
            -   name: Tag images
                run: |
                    docker tag space-guardians-app:local space-guardians-app:latest
            -   name: Start services
                run: docker compose up -d --build --quiet-pull
            -   name: Install Dependencies
                run: docker compose run composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            -   name: Create Database
                run: docker compose run app php bin/console --env=test doctrine:database:create
            -   name: Execute migrations
                run: docker compose run app php bin/console --env=test doctrine:migration:migrate --allow-no-migration --no-interaction
            -   name: Execute tests (Unit and Feature tests) via PHPUnit
                run: docker compose run app php bin/phpunit
